{% set version = "0.1.0" %}
{% set name = "dfviz" %}

package:
   name:  {{ name }}
   version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2beebde99a79bb47a9c1f48ffb61c465ee63b91fbb3d7d689856b6e46b2297e4

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }}  -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - versioneer
  run:
    - bokeh
    - dask
    - panel >=0.5.1
    - hvplot

test:
  requires:
    - python {{ python_min }}
  imports:
    - dfviz

about:
  home: https://github.com/intake/dfrviz
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Interactive visualisation interface for dataframes"

extra:
  recipe-maintainers:
    - martindurant
